# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('userid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('image', models.ImageField(null=True, upload_to='drop_image')),
                ('name', models.CharField(default='', max_length=128)),
                ('total_amount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'BOTH')], default=0)),
                ('max_age', models.IntegerField(default=100)),
                ('min_age', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='drop',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.Filter'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='drop_created',
            field=models.ManyToManyField(related_name='creator', to='apiapp.Drop'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='drop_received',
            field=models.ManyToManyField(related_name='receiver', to='apiapp.Drop'),
        ),
    ]
