# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='drop_created',
            field=models.ManyToManyField(blank=True, related_name='creator', to='apiapp.Drop'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='drop_received',
            field=models.ManyToManyField(blank=True, related_name='receiver', to='apiapp.Drop'),
        ),
    ]
