# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20170610_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='userid',
            new_name='userId',
        ),
    ]
