# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_auto_20170610_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drop',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
