# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20170610_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drop_image'),
        ),
    ]
