# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20170610_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='location',
        ),
    ]
